services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - 127.0.0.1:4000:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:${POSTGRES_PASSWORD}@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      # Disable when it is your second time running it
      - CREATE_ADMIN=0
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=miniflux
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: [CMD, pg_isready, -U, miniflux]
      interval: 10s
      start_period: 30s
    restart: always
